### ISSUE TITLE
UPDATE client SBT v 1.2.3

### ISSUE THREAD

**Issue by Xyypp** [Mouleh/SBT#18]
Download link : https://panel.snowbot.eu/build/SnowBotTouchV1.2.3.zip
Update déjà effectué sur : 
-Rush 1 herde 
-Rush 2 herde 
-Rush 1 terra
-Rush 2 terra

**Comment by Xyypp** [comment]
- Banque terra UPDATE

**Comment by Mouleh** [comment]
Tout les serveurs paysan Herdegrize UPDATE

**Comment by Mouleh** [comment]
Bucheron Herdegrize Update

**Comment by Mouleh** [comment]
Tout les serveurs paysan Terra Update

**Comment by Mouleh** [comment]
Banque Herdegrize update

**Comment by Mouleh** [comment]
Sacri Herdegrize Update

**Comment by Mouleh** [comment]
All servers updated
